### ISSUE TITLE
Support YAML as configuration language

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite#2560]
Bukkit/Spigot also use `config.yml` 's to store the core settings.
Here are the specs: http://yaml.org/

**Comment by NiLSPACE** [comment]
Yeah.. but.. we're not bukkit or spigot..

**Comment by SphinxC0re** [comment]
That is not the point. INI files are way LEDs structured than YAML files. We could shorten configurations files down a little and make Konfiguration overall easier. (Mobile so explaining more later)

**Comment by NiLSPACE** [comment]
Weren't you forced to use spaces in front with yaml? Because that confused me allot when I used to host a server a few years ago.

**Comment by SphinxC0re** [comment]
YAML offers a whole lot of data structures like mappings, lists, lists of mappings, mappings of lists, direct distinction between boolean, number, string, objects, object nesting.
What I want so say is, that it allows us to shrink down our INI files and make configuration easier. Just imagine the normal setting.ini:
```ini
; This is the main server configuration
; Most of the settings here can be configured using the webadmin interface, if enabled in webadmin.ini
; See: http://wiki.mc-server.org/doku.php?id=configure:settings.ini for further configuration help

[Authentication]
Authenticate=1
AllowBungeeCord=0
Server=sessionserver.mojang.com
Address=/session/minecraft/hasJoined?username=%USERNAME%&serverId=%SERVERID%

[MojangAPI]
NameToUUIDServer=api.mojang.com
NameToUUIDAddress=/profiles/minecraft
UUIDToProfileServer=sessionserver.mojang.com
UUIDToProfileAddress=/session/minecraft/profile/%UUID%?unsigned=false

[Server]
Description=Cuberite - in C++!
MaxPlayers=100
HardcoreEnabled=0
AllowMultiLogin=0
Ports=25565
DefaultViewDistance=10

[RCON]
Enabled=0

[PlayerData]
LoadOfflinePlayerData=0
LoadNamedPlayerData=1

[Worlds]
DefaultWorld=world

[Plugins]
; Plugin=Debuggers
; Plugin=HookNotify
; Plugin=ChunkWorx
; Plugin=APIDump
Plugin=Core
Plugin=TransAPI
Plugin=ChatLog

[DeadlockDetect]
Enabled=1
IntervalSec=20
```
And now, YAML:
```yaml
# This is the main server configuration
# Most of the settings here can be configured using the webadmin interface, if enabled in webadmin.ini
# See: http://wiki.mc-server.org/doku.php?id=configure:settings.yml for further configuration help

Authentication:
  Authenticate: true
  AllowBungeeCord: false
  Server: 'sessionserver.mojang.com'
  Address: '/session/minecraft/hasJoined?username=%USERNAME%&serverId=%SERVERID%'

MojangAPI:
  NameToUUIDServer: 'api.mojang.com'
  NameToUUIDAddress: '/profiles/minecraft'
  UUIDToProfileServer: 'sessionserver.mojang.com'
  UUIDToProfileAddress: '/session/minecraft/profile/%UUID%?unsigned=false'

Server:
  Description: 'Cuberite - in C++!'
  MaxPlayers: 100
  HardcoreEnabled: false
  AllowMultiLogin: false
  Ports: 25565
  DefaultViewDistance: 10

RCON:
  Enabled: false

PlayerData:
  LoadOfflinePlayerData: false
  LoadNamedPlayerData: true

Worlds:
  DefaultWorld: 'world'

Plugins:
#  - Debuggers
#  - HookNotify
#  - ChunkWorx
#  - APIDump
  - Core
  - TransAPI
  - ChatLog

DeadlockDetect:
  Enabled: true
  IntervalSec: 20
```
See? Even though, I have to admit, that this did not shrink anything but it is more structured, way more readable and differs between types, so it's more understandable what an option does. Sure it needs whitespaces, but that does a lot good to the structure of the document.
