### ISSUE TITLE
Exit code 139 on startup

### ISSUE THREAD

**Issue by yangm97** [cuberite/cuberite#3424]
Client version:   self-compiled
Server OS:        Alpine 3.4 inside Docker
Commit id:        32b38fb2649fb282b6446c4e544866c0161aa7da

### Expected behavior
Successful startup

### Actual behavior
Container exits with code 139 (seg fault?)

### Steps to reproduce the behavior
Dockerfile
```
FROM alpine:3.4
MAINTAINER Yan Minari <yangm97@gmail.com>

ENV APP_REPO=https://github.com/cuberite/cuberite.git
ENV APP_BRANCH=master
ENV BUILD_TYPE=RELEASE
WORKDIR /tmp

RUN apk add --no-cache --virtual build-dependencies \
    build-base \
    clang \
    cmake \
    git \
    perl &&\
    git clone \
    -b ${APP_BRANCH} \
    --recursive \
    ${APP_REPO} /tmp

RUN cmake . -DCMAKE_BUILD_TYPE=${BUILD_TYPE} && make -j 2

RUN mkdir -p /opt/app && \
    cp -a /tmp/Server/* /opt/app && \
    apk del build-dependencies && \
    rm -rf /tmp/*

RUN apk add --no-cache libstdc++

WORKDIR /opt/app

CMD ["./Cuberite"]
```

docker-compose.yml
```
cuberite:
  build: .
  ports:
   - "25566:25565"
   - "8080:8080"
#  volumes:
#   - ./Server:/opt/app/
  tty: true
  stdin_open: true
```
